broker:
  queues:
    proposals:
      name: proposals
    proposals-notification:
      name: proposals.notification
    pe@nding-proposals-validation:
      name: pending.proposals.validation
    pending-proposals-notification:
      name: pending.proposals.notification

  exchanges:
    proposals:
      name: proposals.exchange
    pending-proposals:
      name: pending.proposals.exchange

  bindings:
    main:
      exchange-name: proposals.exchange
      queue-name: proposals
    notification:
      exchange-name: proposals.exchange
      queue-name: proposals.notification
    pending-validation:
      exchange-name: pending.proposals.exchange
      queue-name: pending.proposals.validation
    pending-notification:
      exchange-name: pending.proposals.exchange
      queue-name: pending.proposals.notification

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:dev
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  rabbitmq:
    addresses: ${QUEUE_URL:${QUEUE_CREDENTIALS:${QUEUE_ADMIN_USERNAME:guest}:${QUEUE_ADMIN_PASSWORD:guest}}@localhost}
